# Generated by Django 4.2.6 on 2023-11-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LavaroWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-last_modified'], name='LavaroWeb_c_last_mo_9ab55c_idx'),
        ),
    ]
